// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1fehxXl4kRggS_2IPFNh5IhD1W97c1Ec',
    appId: '1:291256897659:web:5e5f60b1da109e4537d2de',
    messagingSenderId: '291256897659',
    projectId: 'careconnect-386ae',
    authDomain: 'careconnect-386ae.firebaseapp.com',
    databaseURL: 'https://careconnect-386ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'careconnect-386ae.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVKmUToctOwkxv6Ejyq9vvUBYWQsXpGj0',
    appId: '1:291256897659:android:d388eeaae7afdfb337d2de',
    messagingSenderId: '291256897659',
    projectId: 'careconnect-386ae',
    databaseURL: 'https://careconnect-386ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'careconnect-386ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsetMHFKcDzGCRQ4Wiez08qvN5xBT1PXw',
    appId: '1:291256897659:ios:62910985501855dd37d2de',
    messagingSenderId: '291256897659',
    projectId: 'careconnect-386ae',
    databaseURL: 'https://careconnect-386ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'careconnect-386ae.firebasestorage.app',
    iosBundleId: 'com.example.careconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsetMHFKcDzGCRQ4Wiez08qvN5xBT1PXw',
    appId: '1:291256897659:ios:62910985501855dd37d2de',
    messagingSenderId: '291256897659',
    projectId: 'careconnect-386ae',
    databaseURL: 'https://careconnect-386ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'careconnect-386ae.firebasestorage.app',
    iosBundleId: 'com.example.careconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1fehxXl4kRggS_2IPFNh5IhD1W97c1Ec',
    appId: '1:291256897659:web:7b6a1527715729f737d2de',
    messagingSenderId: '291256897659',
    projectId: 'careconnect-386ae',
    authDomain: 'careconnect-386ae.firebaseapp.com',
    databaseURL: 'https://careconnect-386ae-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'careconnect-386ae.firebasestorage.app',
  );

}